data:
  dataset: "Fusion"
  image_size: 256
  channels: 3
  num_workers: 24
  rescaled: true
  conditional: True

path:
  figure: "figures"
  log: "logs"
  results: "results"
  checkpoint: "checkpoint"
  val_sample: "val_sample"
  test_sample: "test_sample"

model:
  in_channels: 9
  out_ch: 3
  ch: 128
  ch_mult: [ 1, 2, 3, 4 ]
  num_res_blocks: 2
  attn_resolutions: [ 32 ] # 16
  dropout: 0.0
  ema_rate: 0.939 # 0.999
  ema: True
  resamp_with_conv: True

diffusion:
  beta_schedule: linear
  beta_start: 0.0001
  beta_end: 0.02
  num_diffusion_timesteps: 1000

training:
  batch_size: 4
  n_epochs: 10000
  epoch_freq: 100

sampling:
  batch_size: 1
  last_only: True

testing:
  batch_size: 1

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.00002
  amsgrad: False
  eps: 0.00000001
  beta1: 0.9
