data:
  dataset: "Visible"
  image_size: 128
  channels: 3
  num_workers: 24
  rescaled: true
  data_dir: "/data2/wait/bisheCode/DDPM_Fusion/dataset/visible128"
  conditional: True

path:
  root: "/data2/wait/bisheCode/DDPM_Fusion"
  figure: "figures"
  log: "logs"
  checkpoint: "checkpoint"
  train_process: "train_process"
  test_sample: "test_sample"
  val_sample: "val_sample"
  fusion: "Fusion"

model:
  in_channels: 9
  out_ch: 3
  ch: 128
  ch_mult: [ 1, 2, 3, 4 ]
  num_res_blocks: 2
  attn_resolutions: [ 16 ] # 16
  dropout: 0.0
  ema: True
  resamp_with_conv: True

diffusion:
  beta_schedule: linear
  beta_start: 0.0001
  beta_end: 0.02
  num_diffusion_timesteps: 1000

training:
  batch_size: 20
  n_epochs: 10000
  epoch_freq: 100

sampling:
  batch_size: 10
  last_only: True

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.00002
  amsgrad: False
  eps: 0.00000001
  beta1: 0.9
  grad_clip: 5.0 # (1.0-5.0)
